### ISSUE TITLE
Native AOT: WinForms Exception during compilation of method

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1070]
Exception in resolution failure(?)

```
Failed to load assembly 'System.IO.Ports'
   at Internal.TypeSystem.ThrowHelper.ThrowFileNotFoundException(ExceptionStringID id, String fileName) in D:\runtimelab\src\coreclr\tools\Common\TypeSystem\Common\ThrowHelper.cs:line 35
```

This is happening when doing something for `System` assembly. `ResolutionFailure.Throw()` is method which raise exception.

**Comment by jkotas** [comment]
This exception is expected when you have `System` specified in rd.xml or otherwise rooted.

The legacy netstandard facades like `System.dll` have references to assemblies that ship as standalone packages. It is a compromise between compatibility and footprint of the global .NET runtime installation.
