### ISSUE TITLE
WPF require MulticastDelegate

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1107]
This line of code throws https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/UnsafeNativeMethodsMilCoreApi.cs#L155

and this one https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/UnsafeNativeMethodsMilCoreApi.cs#L133 A lot of code in that file has Delegate in the Interop signatures.

Seems to be this was discussed here https://github.com/dotnet/runtimelab/pull/690#discussion_r576981030

**Comment by jkotas** [comment]
What is the error that you see? Does it fail to compile or does it fail at runtime? It is kind of expected that this will fail at runtime since the compiler does not know which delegate to compile for interop without extra hints (attributes or rd.xml).

Are all these PInvokes used with just one signature, or does WPF codebase actually depends on being able to pass different delegate types into these methods? If it is the earlier, it would be best to fix WPF to have concrete delegate types in the PInvoke signatures.

**Comment by kant2002** [comment]
It does not fails per-se, just throw unsupported marshalling and continue. I record that since this is not explicitly mentioned anywhere. Also I will check with WPF how signatures are used. Maybe I really can fix signature there.

**Comment by MichalStrehovsky** [comment]
I think we just need to extend this line

https://github.com/dotnet/runtimelab/blob/b5f7612e2423f55cb265b28ecc04a2ef32c0dc7b/src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs#L505

to also cover System.Delegate and System.MulticastDelegate (IsDelegate means "derives from MulticastDelegate" and won't cover those two).

But yeah, this is going to potentially have trouble at runtime because the compiler might not have generated the delegate marshalling data. But that's then solvable with RD.XML like any other issue.
