### ISSUE TITLE
Question: GenTree identifier

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1260]
In NativeAOT-LLVM the `gtTreeID` is used as a key to lookup LLVM Values, e.g. `GT_STOREIND` is implemented with this

```
void importStoreInd(llvm::IRBuilder<>& builder, GenTreeStoreInd* storeIndOp)
{
    Value* address = getTreeIdValue(storeIndOp->Addr());
    Value* toStore = getTreeIdValue(storeIndOp->Data());
```
where `getTreeIdValue` is looking up the `Value*` based on the `gtTreeID`.  This is not going to work in Release mode as `gtTreeID` is `#if`ed in only for `DEBUG`.  Where a `GenTree` is returned in cases like the one above, `Addr()` and `Data()` is it the same struct as when the node is "created", i.e. with this IR
```
N005 (  1,  4) [000007] H-----------         t7 =    CNS_INT(h) ref    0x420C08 [ICON_STR_HDL]
                                                  /--*  t3     byref
                                                  +--*  t7     ref
```
The `GenTree` for the `CNS_INT`, would it have the same address as the result of `Data()` and therefore can be relied upon like a `GetHashCode()` in .Net or does the compiler create different `GenTree` structs to represent the same node ?

**Comment by jkotas** [comment]
It should be fine to use `GenTree*` as a key lookup. RyuJIT does not create different GenTree structs to represent the same node.

The debug-only `gtTreeID` exists to allow comparing logs between runs. The addresses are often different between different runs due to address space randomization, but `gtTreeID`s are stable.
