### ISSUE TITLE
NativeAOT:How to fix MongoDB.Driver infinite generic expansion?

### ISSUE THREAD

**Issue by loyldg** [dotnet/runtimelab#1304]
I am using MongoDB.Driver(Clone code to local),and have two problems in AOT compilation.
1.Catching generic exceptions
2.Infinite generic cycle,mentioned at this link https://github.com/dotnet/corert/issues/8232#issuecomment-660278463
The first issue can be fixed using exception filter "catch (Exception ex) when (ex is T)"
I don't know how to fix the second one,any suggestions?

**Comment by jkotas** [comment]
I have looked at refactoring the MonoDB code to avoid the generic cycles cleanly, but I was not able to figure out how to do that. 

I would first identify all places that lead to the cycles. For example, does the compilation finish if you comment out all bodies of `WithPipeline<TNewResult>` methods?

Since the cycles seem to be all composed from reference types, you can try fix them by using reflection to instantiate the generic types. For example, replace `return new CollectionAggregateFluent<TDocument,TNewResult>(...)` with:
```
readonly static Type s_Type = type(CollectionAggregateFluent<,>);

...

Type t = s_Type.MakeGenericType(new Type[] { typeof(TDocument), typeof(TNewResult) });
return (IAggregateFluent<TNewResult>)Activator.CreateInstance(t, new object[] { _session, _collection, pipeline, _options });
```

This hack is mimicking what the compiler would do for you if https://github.com/dotnet/runtimelab/issues/537 is fixed. Fixing https://github.com/dotnet/runtimelab/issues/537 would be another to resolve this issue.

**Comment by loyldg** [comment]
Thank you for your help.
I found two pieces of code makes AOT compilation unable to complete:

1. https://github.com/mongodb/mongo-csharp-driver/blob/94a1febff995b2f6d137ee56bd9b9b7b33f3e50a/src/MongoDB.Driver/AggregateFluent.cs#L348

2. https://github.com/mongodb/mongo-csharp-driver/blob/94a1febff995b2f6d137ee56bd9b9b7b33f3e50a/src/MongoDB.Driver/AggregateFluent.cs#L423

Currently I fixed the compilation issue:using reflection to instantiate the generic types.

CollectionAggregateFluent.WithPipeline
```c#
private static readonly Type s_Type = typeof(CollectionAggregateFluent<,>);
protected override IAggregateFluent<TNewResult> WithPipeline<TNewResult>(PipelineDefinition<TDocument, TNewResult> pipeline)
        {
            Type t = s_Type.MakeGenericType(typeof(TDocument), typeof(TNewResult));
            return (IAggregateFluent<TNewResult>)Activator.CreateInstance(t, _session, _collection,
                pipeline,
                _options);
            //throw new NotImplementedException();
            //return new CollectionAggregateFluent<TDocument, TNewResult>(_session, _collection, pipeline, _options);
        }
```

DatabaseAggregateFluent.WithPipeline
```c#
private static readonly Type s_Type = typeof(DatabaseAggregateFluent<>);
protected override IAggregateFluent<TNewResult> WithPipeline<TNewResult>(PipelineDefinition<NoPipelineInput, TNewResult> pipeline)
        {
            Type t = s_Type.MakeGenericType(typeof(TNewResult));
            return (IAggregateFluent<TNewResult>)Activator.CreateInstance(t, _session, _database,
                pipeline,
                _options);
            //throw new NotImplementedException();
            //return new DatabaseAggregateFluent<TNewResult>(_session, _database, pipeline, _options);
        }		
```

**Comment by jkotas** [comment]
Thank you for sharing the workaround. Let's use #537 to track the fix in the AOT compiler.
