### ISSUE TITLE
[NativeAOT] undefined references when using static linking

### ISSUE THREAD

**Issue by andreakarasho** [dotnet/runtimelab#1342]
macOS Mojave 10.14
```Undefined symbols for architecture x86_64:
           "___isPlatformVersionAtLeast", referenced from:
               _AppleCryptoNative_EccGenerateKey in libSystem.Security.Cryptography.Native.Apple.a(pal_ecc.c.o)
               _AppleCryptoNative_RsaGenerateKey in libSystem.Security.Cryptography.Native.Apple.a(pal_rsa.c.o)
           "_kSecUseDataProtectionKeychain", referenced from:
               _AppleCryptoNative_EccGenerateKey in libSystem.Security.Cryptography.Native.Apple.a(pal_ecc.c.o)
               _AppleCryptoNative_RsaGenerateKey in libSystem.Security.Cryptography.Native.Apple.a(pal_rsa.c.o)
```
Tried to add `<NativeLibrary Include="-framework Security" />` but did not help

**Comment by jkotas** [comment]
Could you please share more complete steps to reproduce the problem?

**Comment by andreakarasho** [comment]
I prepared a test case.
Compile it with: `dotnet publish -c Release -r osx-x64`

[Archive.zip](https://github.com/dotnet/runtimelab/files/6836386/Archive.zip)

**Comment by filipnavara** [comment]
These symbols come from the Apple weak symbol logic. The native toolchain generates the `__isPlatformVersionAtLeast` method and the other symbol should be weakly linked (exists on newer macOS version though).

`System.Security.Native.Apple` uses the clang feature to enable targeting multiple OS versions. Due to some platform restrictions for upload to app store this approach is preferred over manual `dlopen`/`dlsym`. It is also much easier to write with the C extensions.

**Comment by filipnavara** [comment]
More details at https://github.com/dotnet/runtime/pull/52759#discussion_r632884815

**Comment by jkotas** [comment]
I am not able to reproduce this on BigSug 11.4 + XCode 12.5. 

@andreakarasho What is the XCode version that you are using?

This looks similar to https://github.com/curl/curl/issues/4314 that suggests that this is a problem with the XCode versions being used.

**Comment by andreakarasho** [comment]
I updated to Mojave 10.14.6 and then installed XCode 11.3.1
still getting the issue.

I think macOS 10.15 is needed:
```if (__builtin_available(macOS 10.15, iOS 13, tvOS 13, *))```

**Comment by andreakarasho** [comment]
Updating to BigSur 11.4 fixed the issue

**Comment by filipnavara** [comment]
> I think macOS 10.15 is needed:
if (__builtin_available(macOS 10.15, iOS 13, tvOS 13, *))

That's not how `__builtin_available` works. I posted a link to the explanation above. If you target macOS < 10.15 it will insert dynamic check and use weak linking for the new APIs. If you target macOS >= 10.15 it will use regular strong linking and the code becomes `if (true)`.

So maybe the problem just gets hidden because the SDK default is to target the current macOS version and NativeAOT does not override it?

**Comment by jkotas** [comment]
> Updating to BigSur 11.4 fixed the issue

What is the XCode version that you have used on BigSur 11.4?

**Comment by andreakarasho** [comment]
I didn’t installed xcode directly.
This is what i did:
- installed brew
- Installed git (here brew automatically installed the xcode cmd tool)
- installed cmake
- Installed clang 
- compiled the app

**Comment by jkotas** [comment]
Where are you getting the libraries for static linking from in this setup? If you are getting the ones the come with the OS and not the ones that come with Apple SDK, it would explain the problem. 

We only support building with XCode. For custom setups like this, you are on your own.

**Comment by andreakarasho** [comment]
sdl and fna  compiled with cmake with the same OS
