### ISSUE TITLE
Activator.CreateInstance broken (?)

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1373]
After https://github.com/dotnet/runtimelab/pull/1347 PropertyGrid on Winforms applicaion starts to crash,

Line where it crashing is somewhere here
https://github.com/dotnet/winforms/blob/6515f5ff8b3a7b314fd7bed1ff8852b5efb3ce19/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs#L1726-L1733

Reason why I'm saying somewhere here is that this method has somewhat convoluted assembly and debugger messed up and point on first part of if, but when run under CoreCLR it's executed `tab = (PropertyTab)Activator.CreateInstance(tabType);`. Crash happens at `SampleWindowsForms!S_P_Reflection_Core_System_ActivatorImplementation__CreateInstance+0xeb` so again most likely System.Activator.CreateInstance involved.

`tabType == typeof(System.Windows.Forms.PropertyGridInternal.PropertiesTab)`

That's without my usual `<IlcDisableReflection>false</IlcDisableReflection>`. So reflection should works there.

Exception what happening is `Arg_IndexOutOfRangeException`

If I add 
```
<Assembly Name="System.Windows.Forms">
  <Type Name="System.Windows.Forms.PropertyGridInternal.PropertiesTab" Dynamic="Required All" />
</Assembly>
``` 
I receive `Arg_NoDefCTor`

I was trying to add
```
<Assembly Name="System.Windows.Forms">
  <Type Name="System.Windows.Forms.PropertyGridInternal.PropertiesTab" Dynamic="Required All">
    <Method Name=".ctor" Dynamic="Required All" />
  </Type>
</Assembly>
```

but that does not helps either.

**Comment by MichalStrehovsky** [comment]
What other settings do you have in the project file? Any method body folding, etc.?

When you say debugger is messed up, is this an optimized build? Unoptimized should me much easier to reason about if the problem is around missing constructors.

**Comment by kant2002** [comment]
Seems to be `--reflectedonly` is the culprit.

**Comment by kant2002** [comment]
And specific line which throw is https://github.com/dotnet/winforms/blob/6515f5ff8b3a7b314fd7bed1ff8852b5efb3ce19/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs#L1733

**Comment by MichalStrehovsky** [comment]
`--reflectedonly` would eliminate reflection metadata for constructors that were compiled but otherwise not visibly used from reflection. So CreateInstance failing is plausible. `Arg_IndexOutOfRangeException` is still suspicious through.

RD.XML not helping usually means one of two things:
* It's not getting picked up by the compiler, or
* The type in question is actually a different type. If you have it under a debugger, the type name can be usually dug out using VS if you click around enough (disable optimizations for a good debug experience)
