### ISSUE TITLE
InvalidProgramException during type pre-init

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#1403]
I receive exception at function
`[S.P.CoreLib]System.DateTime.DateToTicks(int32,int32,int32)` during PreInit
https://github.com/dotnet/runtimelab/blob/4ffe2eb2b6c972697fa3888620bca27e6c391578/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/TypePreinit.cs#L1345

This happens when those compiling those classes 
```
{[S.P.CoreLib]System.Globalization.HijriCalendar}
{[S.P.CoreLib]System.Globalization.JapaneseCalendar}
{[S.P.CoreLib]System.Globalization.HebrewCalendar}
{[S.P.CoreLib]System.Globalization.PersianCalendar}
{[S.P.CoreLib]System.Globalization.UmAlQuraCalendar}
{[S.P.CoreLib]System.Globalization.CalendricalCalculationsHelper}
```

**Comment by kant2002** [comment]
Admittedly I hit that when compile using 5.0.7 libs, so maybe not applicable anymore, since I cannot repro right now with .NET 6.0

**Comment by kant2002** [comment]
Additional information, if this is transfered to question
```
array.Value is ILCompiler.TypePreinit.ForeignTypeInstance
array.Value.Data is ArrayInstance
array.Value.ForeignField {[S.P.CoreLib]System.DateTime.s_daysToMonth365}
array.Value.Type {uint32[]}
```
What `ForeignTypeInstance` means, and why this kind of constructs cannot be processed by ILC?

**Comment by MichalStrehovsky** [comment]
This is in the IL interpreter that runs static constructors at compile time.

`ForeignTypeInstance` means that this is an object that was allocated from a different static constructor (not the one we're currently interpreting). We're hitting this exception because the static constructor we're currently interpreting would like to read an element of such array. We don't allow doing that - the array could be modified before this static constructor is supposed to run at runtime and the compile-time preinitialization would be observable.

The InvalidProgramException will get caught and results in not preinitializing the type. Admittedly, we could also just handle the `array.Value is ForeignTypeInstance` case and have it do `return Status.Fail(methodIL.OwningMethod, opcode, "Foreign array");` The end result is going to be same though - type not preinitialized. If it's annoying to see the first chance exception in the debugger, we should add handling.

**Comment by kant2002** [comment]
Yes. It is annoying, but my annoyance is not important. I personally thing that "well-known not handled cases" should be handled without exception, but I fear that it may hinder debuggability for people who don't know domain well.
Right now I have exception and I can ask question, but at the same time, answer would be always the same. This is explicitly not supported for "such and such reasons".
So I in favor of explicit case, but worry that I miss something from support perspective where you have more experience.

If you think that `return Status.Fail(methodIL.OwningMethod, opcode, "Foreign array");` is way to go, I can submit PR.

**Comment by MichalStrehovsky** [comment]
> If you think that return Status.Fail(methodIL.OwningMethod, opcode, "Foreign array"); is way to go, I can submit PR.

Yes please!
