### ISSUE TITLE
[NativeAOT-LLVM] Question: Rewriting signatures to include the shadow stack

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1708]
Thinking about moving the shadow stack arg processing on the arg list and in managed calls, from the LLVM build step to a lowering step.  The signature for the function being compiled is retrieved from Ilc, starting at https://github.com/dotnet/runtimelab/blob/9d54885c319c09817e90928e96bd88382726907d/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs#L802

I'm thinking that modifying the `CORINFO_SIG_INFO` and its `args` leads to some handling for the shadow stack in `https://github.com/dotnet/runtimelab/blob/9d54885c319c09817e90928e96bd88382726907d/src/coreclr/tools/aot/ILCompiler.RyuJit/JitInterface/CorInfoImpl.Llvm.cs#L196`.  

Is that the right way to go?

cc @SingleAccretion
cc @jkotas 

The modification of the actual IR `CALL`s seems more straightforward.

**Comment by SingleAccretion** [comment]
Hmm, the signature is also consulted by the frontend, seems risky to modify it (or is that not what you're thinking about?).

It would be less invasive to have our own internal `CallSignature` structure that would represent the same thing but with the flexibility that we will need. Lowering would then populate it and hang off the call node (say in a side table) for codegen to use in building the LLVM's equivalent (this also implies that this signature would be identical to the "final" version). There is quite a bit of handling present in various places for non-standard args, those would also be present in the signature.

Alternatively, we could insert special nodes in the IR for call arguments that represent their final destination (arg number) and type. Since we can be passing `TYP_REF`s  into calls that expect `TYP_STRUCT`s with struct promotion, we will need to represent these effective `BITCAST`s somehow anyway. The downside is it requires more space IR-wise and adding some LLVM-specific fields to the `GenTreePutArgType` nodes, but we can probably live with this.

**Comment by yowl** [comment]
> we could insert special nodes in the IR for call arguments

This sounds interesting, I'll try that, thanks.
