### ISSUE TITLE
[NativeAOT-LLVM] [Question] consuming return values from CT_INDIRECT

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1862]
Looking at this IR:
```
                                                  /--*  t84    int    arg-1
                                                  +--*  t32    int    calli tgt
N006 ( 26, 11) [000029] --CXG-------        t29 = *  CALL ind  int
                                                  /--*  t29    int
N008 ( 30, 14) [000027] DA-XG-------              *  STORE_LCL_VAR int    V05 tmp3         d:4```
```
`t29` is stored in the sdsu map as an `i8`, and then fails to be consumed to an `int` for the `STORE_LCL_VAR`.

@SingleAccretion, previously you wrote

> To maintain the invariant under 1 (only exact types stored in locations), we are to pass the type of the local to consumeValue (and ignore the node type).

Is this the erroneous logic in `consumeValue` at

https://github.com/dotnet/runtimelab/blob/258c8cee8cec40849127995fee955c117ced3d42/src/coreclr/jit/llvm.cpp#L923

Should that be using `targetLlvmType` which comes from the type of the local?

**Comment by SingleAccretion** [comment]
It seems to me the problem is that we once again have an IR node that's effectively lying about its true type (the call). We could retype the call in lowering to the small type or add one more special case to `consumeValue` (if `OperIs(GT_CALL) {/* use gtReturnType as the source of truth */`). I would be inclined to do the latter for now (we should clean up all these small types at some point, but probably not now).
