### ISSUE TITLE
[NativeAOT-LLVM]  [WASM] Cross-OS native compilation is not supported

### ISSUE THREAD

**Issue by inkeliz** [dotnet/runtimelab#1961]
I'm trying to compile to WASM, using the following command line:

```
dotnet publish -r browser-wasm -c Debug /p:TargetArchitecture=wasm /p:PlatformTarget=AnyCPU /p:MSBuildEnableWorkloadResolver=false --self-containe
```

However, that returns:

```
C:\Users\lucas\.nuget\packages\microsoft.dotnet.ilcompiler\7.0.0-preview.7.22375.6\build\Microsoft.NETCore.Native.Publi
sh.targets(54,5): error : Cross-OS native compilation is not supported. [X:\karmem\benchmark\dotnetllvm\dotnetllvm.cspr
oj]
```

Assuming that WASM is always cross-compile, how I can enable that?

--------------

CSPROJ:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-*" />
    <PackageReference Include="Microsoft.DotNet.ILCompiler.LLVM">
      <Version>7.0.0-*</Version>
    </PackageReference>
    <PackageReference Include="runtime.win-x64.Microsoft.DotNet.ILCompiler.LLVM">
      <Version>7.0.0-*</Version>
    </PackageReference>
  </ItemGroup>

</Project>
```

NuGet Config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="dotnet-experimental" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json" />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

EMCC:

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.12 (38d1292ba2f5b4a7c8518931f5ae6f97ef0f6827)
clang version 15.0.0 (https://github.com/llvm/llvm-project d58cc0839ee5935e649dbbc18c898a8e4bcd6724)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Comment by yowl** [comment]
The only package reference you should have is 
```
<PackageReference Include="Microsoft.DotNet.ILCompiler.LLVM; runtime.win-x64.Microsoft.DotNet.ILCompiler.LLVM" Version="7.0.0-*" />
```
Can you remove the others?

**Comment by inkeliz** [comment]
That works, thanks. Also, I notice that the it compiles to `browser-wasm`. Have any option to compile to `none-wasm` or `freestanding-wasm` or `wasi-wasm`? Anything that doesn't require the JS glue (and doesn't require browser).

**Comment by yowl** [comment]
There is no other runtime identifier for Wasm in dotnet (unfortunately).  I did some work on WASI -controlling a Raspberry Pi, but it is not merged https://github.com/dotnet/runtimelab/pull/1850.  There's some write up: https://github.com/yowl/wasmpi and a little video: https://twitter.com/yowl00/status/1491737713095196679.

Steve Sanderson has also been pushing the official wasm compiler forward for WASI.  I don't have links to his posts to hand unfortunately.

**Comment by inkeliz** [comment]
Have any specific reason for not merge that PR? 

-----

Currently, I'm using the the Steve Sanderson project (https://github.com/SteveSandersonMS/dotnet-wasi-sdk). That works, but is very slow (it's at best: 200x slower than C, 100x slower than TinyGo and 8x slower than SwiftWasm). Furthermore, it doesn't support garbage-collector (causing crashes), doesn't seems to grow the memory dynamic (it doesn't calls "grow" to the runtime, and have fixed amount of memory) and it doesn't support AOT. It also requires some C code to import/export functions. 

So, in general, that is one interesting project, but not fit my use case, it's slow and unstable. I'm not sure if NativeAOT-LLVM will fix that, but since it's AOT: the performance is expected to be better and I guess it will support GC, preventing crashing.

Personally, I don't use C#. I'm just porting one library to C#, in order to make possible to use C# in the WASI environment. 

--------

I notice that the JS code contains alot of:

```
  "invoke_iii": invoke_iii,
  "invoke_iiii": invoke_iiii,
  "invoke_iiiii": invoke_iiiii,
  "invoke_iiiiii": invoke_iiiiii,
  "invoke_iiiiiii": invoke_iiiiiii,
  "invoke_iiiiiiii": invoke_iiiiiiii,
  "invoke_iiiiiiiiii": invoke_iiiiiiiiii,
  "invoke_iiiiiiiiiii": invoke_iiiiiiiiiii,
  "invoke_iiiiiiiiiiiiiiiiiiiiiiii": invoke_iiiiiiiiiiiiiiiiiiiiiiii,
  ```
  
 I'll try to proxy those imported calls, in order to understand what it's doing. Then, I'll try to create some "stub-functions" in the WASM-Runtime, just to satisfy the C# imported functions. Have any document with one list of functions imported the C#/NativeAOT (rather than looking at the JS code)?

**Comment by yowl** [comment]
The PR was not merged because I wasn't sure if it was a great solution to the problem it fixes (dfferent constant values between muslc and cloudlibc).  Jan mentioned that as a short time fix it would probably get accepted.  It does allow the GC.

Note however that NativeAOT-LLVM is just an experiment, there's not been a lot of progress on it recently as I've not had the time (I dont work for Microsoft, and I do it only when I have the time).  There's other people who contribute, but not so much on the coding side, more on review, suggestions, general help.

Those `invoke`s are calls that emscripten has decided it needs to invoke from javascript - because they can't be supported in Wasm.  If you are not compiling without wasm-exceptions (and NativeAOT-LLVM does not use wasm-exceptions yet), then a method that uses exceptions will fall into that category.  I think when I did the WASI stuff I didn't have any exception code so that was not a problem.  NativeAOT-LLVM could move to wasm-exceptions but its a bit of work.   ( the letters after the _ are the return value and args, so `iii` is basically `int func(int, int)  v for void, d for double...`

I don't have a list of all possible imports that emscripten can generate, https://github.com/dotnet/runtimelab/pull/1850/files#diff-510260eed3d716a8332b0db4b9dd021a81356a1375b6593b3db6bd40401e1bf4R116 is somewhere to start.
