### ISSUE TITLE
NativeAOT-LLVM: support wasm exceptions

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#1983]
We should support wasm-exceptions instead of exceptions through javascript (Emscripten exceptions).  This will allow exception support in non javascript hosts and should make the code a bit smaller.
This C++
```cpp
#include <stdio.h>

void throws()
{
  throw 1;
}

int main() {
  try {
    throws();
  } catch(...) {
    puts("catch!");
  }
  return 0;
}

```

Goes to this LLVM as a guide
```ll

@_ZTIi = external constant ptr
@.str = private unnamed_addr constant [7 x i8] c"catch!\00", align 1, !dbg !0

define dso_local void @_Z6throwsv() #0 !dbg !19 {
  %1 = call ptr @__cxa_allocate_exception(i64 4) #2, !dbg !23
  store i32 1, ptr %1, align 16, !dbg !23
  call void @__cxa_throw(ptr %1, ptr @_ZTIi, ptr null) #5, !dbg !23
  unreachable, !dbg !23
}

declare ptr @__cxa_allocate_exception(i64)

declare void @__cxa_throw(ptr, ptr, ptr)

define dso_local noundef i32 @main() #1 personality ptr @__gxx_wasm_personality_v0 !dbg !24 {
  %1 = alloca i32, align 4
  %2 = alloca ptr, align 8
  store i32 0, ptr %1, align 4
  invoke void @_Z6throwsv()
          to label %15 unwind label %3, !dbg !28

3:                                                ; preds = %0
  %4 = catchswitch within none [label %5] unwind to caller, !dbg !30

5:                                                ; preds = %3
  %6 = catchpad within %4 [ptr null], !dbg !30
  %7 = call ptr @llvm.wasm.get.exception(token %6), !dbg !30
  store ptr %7, ptr %2, align 8, !dbg !30
  %8 = call i32 @llvm.wasm.get.ehselector(token %6), !dbg !30
  br label %9, !dbg !30

9:                                                ; preds = %5
  %10 = load ptr, ptr %2, align 8, !dbg !30
  %11 = call ptr @__cxa_begin_catch(ptr %10) #2 [ "funclet"(token %6) ], !dbg !30
  %12 = invoke i32 @puts(ptr noundef @.str) [ "funclet"(token %6) ]
          to label %13 unwind label %16, !dbg !31

13:                                               ; preds = %9
  call void @__cxa_end_catch() [ "funclet"(token %6) ], !dbg !33
  br label %14, !dbg !33

14:                                               ; preds = %13, %15
  ret i32 0, !dbg !34

15:                                               ; preds = %0
  br label %14, !dbg !30

16:                                               ; preds = %9
  %17 = cleanuppad within %6 [], !dbg !33
  invoke void @__cxa_end_catch() [ "funclet"(token %17) ]
          to label %18 unwind label %19, !dbg !33

18:                                               ; preds = %16
  cleanupret from %17 unwind to caller, !dbg !33

19:                                               ; preds = %16
  %20 = cleanuppad within %17 [], !dbg !33
  call void @_ZSt9terminatev() #6 [ "funclet"(token %20) ], !dbg !33
  unreachable, !dbg !33
}

declare i32 @__gxx_wasm_personality_v0(...)
declare ptr @llvm.wasm.get.exception(token) #2
declare i32 @llvm.wasm.get.ehselector(token) #2
declare i32 @llvm.eh.typeid.for(ptr) #3
declare ptr @__cxa_begin_catch(ptr)
declare i32 @puts(ptr noundef) #4
declare void @__cxa_end_catch()
declare void @_ZSt9terminatev()
```
https://godbolt.org/ can be used to try other C++ examples with the options `-S -emit-llvm -fwasm-exceptions`

**Comment by SingleAccretion** [comment]
Summary of the results of my research on this topic (part 1 of N).

A few useful links:
1) Exception handling support in LLVM: https://llvm.org/docs/ExceptionHandling.html.
2) Talk by the people who implemented Windows EH in LLVM about it: https://www.youtube.com/watch?v=9TlR9hNZbck.
3) LLILC EH document: https://github.com/dotnet/llilc/blob/main/Documentation/llilc-jit-eh.md.
4) WASM EH: https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md4

First, let's recall what makes things difficult: the two-pass EH semantic. When an exception is thrown, we enter the first pass. There exists a dynamic stack of active protected regions above the throw site, each with their own handler. For the first pass, we are only interested in filters, i. e. finding the first `catch` that will handle the exception. To do that we walk the stack of handlers with filters, bottom-up, and ask them whether they will handle the exception.

There are two kinds of filters: static and dynamic. Static filters are very simple `is`-like expressions which can be encoded directly into `catch`es. Dynamic filters, on the other hand, are represented via code and called by the EH dispatcher.

Once a filter is found, the second pass proceeds, logically unwinding through the frames, calling any `finally`s and `fault`s in the dynamic stack of handlers, until finally reaching the `catch` found by the first pass.

All in all, the order of execution will look like this:
```
1) Exception is thrown
2) The stack of filters is "unwound" until a suitable catch is found
3) The stack of finallys and faults is unwound
```
Crucially, we can see that we must be able to enumerate the active handler stack twice.

In contrast, both C++ and WASM exceptions only allow for a single pass (`3` above). This is, of course, because all "filters" in ISO C++ are static (have no side effects). This means we cannot use the underlying WASM EH mechanism directly, since it fundamentally only allows for one, destructive, unwind.
