### ISSUE TITLE
Question: NativeAOT-LLVM: GT_ARR_LENGTH semantics

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2061]
Is there any difference between `GT_IND` and `GT_ARR_LENGTH` for LLVM?  If I remember rightly, the length is in the first 4 bytes so a `GT_IND` for an `int` should get the length.  Or does GT_ARR_LENGTH imply something additional, e.g. a null ref check?

**Comment by SingleAccretion** [comment]
> does `GT_ARR_LENGTH` imply something additional, e.g. a null ref check?

(All indirections do, this is something we'll need to implement)

> `GT_ARR_LENGTH`

Is essentially `IND(addr + offset [ specified in the node ])`.

> the length is in the first 4 bytes 

Of the object, yes, but there is still the method table pointer, that's the `offset` part.

One of the ways to deal with this problem is to enable `fgSimpleLowering` for LLVM, it will rewrite `ARR_LENGTH` nodes for us.

However, a full IR walk for a couple nodes does not seem terribly efficient, so we can also lower it ourselves.

**Comment by yowl** [comment]
Thanks,
