### ISSUE TITLE
NativeAOT-LLVM: package publishing is not working

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2166]
I don't know what's best here, do you want to wait until I've done more merging so we are not fixing this only for me to break it again?

**Comment by jkotas** [comment]
I think it is better to keep fixing the small breaks as they occur instead of trying to fix many intertwined breaks at the end. We can keep this opened to keep track of all breaks, just ping me here anytime you notice that the package publishing is broken. 

The current break should be fixed by #2167

**Comment by yowl** [comment]
Thanks, that fixed it.
