### ISSUE TITLE
How can I use this repo to replace a web extension in JavaScript?

### ISSUE THREAD

**Issue by zydjohnHotmail** [dotnet/runtimelab#2249]
Hello:
I have a web extension in JavaScript, basically it is a blockchain wallet, which send RPC calls to RPC server, view, send, sign some blockchain transactions.
There are multiple files, including manifest.json, the background JS file and user interface JS files.
I want to know if I can use this repo to re-write the web extension in JavaScript, so I can run and debug it in a web browser in my Windows 10 PC.
If possible, then please provide some general ideas on how to proceed.
If there is any tutorial on this topic, please provide the link, so I can take a look.
Thanks,

**Comment by yowl** [comment]
I assume you meant "re-write the web extension in c#" ?   I also assume you mean the NativeAOT-LLVM branch here for WebAssembly compilation?  

If so, first thing to note is that the NativeAOT-LLVM branch is experimental and not supported outside of the community.  There are no plans (that I know of, I'm a contributor, but don't work for Microsoft) to merge this upstream to the main runtime repo.  

From a technical point of view what you are asking is possible, however the JS/UI interaction is going to be work.  It might be easier, if you wanted to use NativeAOT-LLVM and not mono, to adapt an existing UI framework like Blazor, Uno, (Avalonia?) to use NativeAOT-LLVM rather than write your own UI.

There's no tutorials on the UI/Javascript side that I can think of, you basically need to track objects that you create JS side and have handles to them in the c# side, at least that is one approach until Wasm gets the component model more advanced to allow you to use the DOM directly.

**Comment by zydjohnHotmail** [comment]
Hello:
Yes, I want to re-write a web extension in JavaScript using C#.
I have no plan to use it in production, but I want to know how to debug something.  Some JavaScript use packages, like: axios to send RPC command to RPC server to get data, like get account balance.  But from browser developer tools, I can't find how the browser extension send the request, I can't see any network pacakges from developer tools.  I didn't try other options yet, like: wireshark. 
I want to know if there is any tools to find out how the web extension, a wallet sends the RPC requests. I want to know the RPC server IP, port number and what the RPC post request payload, the wallet sends.  When running wallet in browser, it is difficult if not impossible to get the above information.  But I have no experience with C# running in web assembly, however I have enough experience for debug C# code in Visual Studio.
Please advise,

**Comment by yowl** [comment]
The network tab in the browsers debugging tools is not sufficient for this?  The problem with debugging this at the source code level with NativeAOT-LLVM is that the variable display is limited at present so getting the payload would be difficult I think.

**Comment by zydjohnHotmail** [comment]
Hi,
Thanks for your reply.
