### ISSUE TITLE
.Net will get better and better, and recommend a JSON library . [Swifter.Json]

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/runtimelab#24]
Hello everyone!  I recommend a JSON library；[https://github.com/Dogwei/Swifter.Json](https://github.com/Dogwei/Swifter.Json)
This is supposed to be the fastest-performing JSON on earth, and it has a full range of functions. I recommend it. You may not like such exaggeration, but it is certainly excellent compared to the performance of JSON libraries in different programming languages. It use Emit and Unsafe.

**Comment by jkotas** [comment]
You library is hacking on .NET runtime internals in unsupported way: https://github.com/Dogwei/Swifter.Json/blob/master/Swifter.Core/Tools/Type/MethodTable.cs

I highly NOT recommend anybody to use it.

**Comment by Dogwei** [comment]
HI @jkotas , I am the author of Swifter.Json. First, thank my good friend @NMSAzulX  for publishing this ad😄.
The reason why Swifter.Json is faster is because Swifter.Core improves the performance of reflection. The principle of improvement is:
Property: By creating delegates of getter and setter, and then calling the delegate to improve performance.
Field: Get the offset of the field, and then use ```Unsafe.AddByteOffset(ref Unsafe.As<ClassBox<TField>>(object).Value, offset)``` to improve performance.
It is easy to create a delegate, but getting the offset of the field is more complicated. I get it in three ways:
1: Get metadata information (ie MethodTable, FieldDesc, EEClass, etc.), and then verify the validity of these values to decide whether to enable it.
2: By modifying the value of the field, and then retrieving the value in the memory of the object to obtain the offset of the field.
3: Obtained through ldflda of Emit.

These three methods have their own limitations:
1 -- usually only available on Core and Framework.
2 -- requires an available ```object Allocate (Type type)``` method.
3 -- must be JIT.

apart from this, Swifter did not use metadata information for other purposes, and did not try to modify metadata information.

If you don't like it, I can remove method 1 so that sensitive classes such as MethodTable are not needed in Swifter.Core. This will not affect the functionality of Swifter.

However, I may not be able to update in the near future because I am busy with company work😭.

**Comment by jkotas** [comment]
The layout of MethodTable, FieldDesc, EEClass, etc. is not stable. It would be great if you can remove the dependency on it from your library.
