### ISSUE TITLE
Can the crossgen2's type-system be used by RuyJIT in future?

### ISSUE THREAD

**Issue by am11** [dotnet/runtimelab#257]
Background: I read somewhere that there is a (passive) desire to replace native implementation of type-system in coreclr with managed, and it may or may not happen in the foreseeable future.

In my understanding, the (relatively) new crossgen2's managed type-system focuses solely on AOT scenarios, which is separate from the native one implemented under coreclr/src/vm that interacts with RuyJIT. Due to that, the new IL features are currently implemented in both the managed (for crossgen2) and native (for JIT and soon-to-be-deprecated crossgen) implementations.

Few questions:
* Is my understanding correct? :)
* Assuming that is the case, when the managed type-system will reach same parity with the native one, are there plans to evolve the managed implementation such that it can also replace all sorts of type-system related bits under VM?
* What are the few most significant feature differences in both type-systems, in terms of cost to make managed type-system suffice both AOT and JIT requirements?
  * Is partial loading of types one of them (i.e. it is available only in VM)?

**Comment by MichalStrehovsky** [comment]
The managed type system is not lean enough to support "execution time" type system operations. CoreCLR's type system is tuned for tiny memory footprint & working set, to the extent that it avoids using virtual methods because of the vtable overhead. Switching to the C#-based one would be a net regression. The type system also needs to support GC operations, and having the GC operate on top of garbage collected data structures would be _interesting_.

The "crossgen2 type system" (it was actually designed for CoreRT, when CoreRT was still called FlexCLR) is tuned for perf and readability. It's quite lean, but not lean to the extent of being [difficult to maintain](https://github.com/dotnet/runtime/issues/6924#issuecomment-547078135).

The managed type system is best suited for things that it's used for right now: crossgen2, CoreRT's AOT compiler, ILVerify, and the CoreRT runtime type loader.

The CoreRT runtime type loader is a pretty interesting use case - CoreRT has a lean type system for runtime execution (to support things like casting, interface dispatch, GC, etc.) that is actually leaner than the one in CoreCLR. CoreRT loads the managed type system when new lean data structures have to be generated at runtime (e.g due to `MakeGenericType`, or as part of the experimental JIT/interpreter operations). Once the managed type system is done building the efficient data structures, it can be garbage collected. This tandem works great as long as loading new types is a rare event. Once it happens too often, the overhead of two type systems running in parallel will start to show up as a problem in profiles. CoreCLR is the dynamic runtime - I don't think such setup would fly there.

**Comment by am11** [comment]
Thanks @MichalStrehovsky for the write up! The 'Pentinum MMX' era lowlevel optimizations in typesystem are still paying off; if that is the perf. bar, then it is indeed too high for C# to compete. :(
