### ISSUE TITLE
[NativeAOT-LLVM] CI Linux machine running low on memory

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#2700]
Recently, we have started getting these messages when running the "Build and run WebAssembly libraries tests" step on Linux

```
  ILC: Method '[S.P.CoreLib]Interop+JsGlobalization.GetLocaleInfo(char*,int32,char*,int32,char*,int32,int32&)' will always throw because: Invalid IL or CLR metadata in 'IntPtr JsGlobalization.GetLocaleInfo(Char*, Int32, Char*, Int32, Char*, Int32, Int32 ByRef)'
  LLVM compilation to IR finished in 249.4 seconds
  LLVM generation of bitcode finished in 50.56 seconds
  Object writing finished in 28.02 seconds, allocated 1145.66 MB
##[warning]Free memory is lower than 5%; Currently used: 95.22%
##[warning]Free memory is lower than 5%; Currently used: 95.22%
##[warning]Free memory is lower than 5%; Currently used: 95.22%
##[warning]Free memory is lower than 5%; Currently used: 95.22%
##[warning]Free memory is lower than 5%; Currently used: 95.22%
##[warning]Free memory is lower than 5%; Currently used: 95.22%
##[warning]Free memory is lower than 5%; Currently used: 95.22%
##[warning]Free memory is lower than 5%; Currently used: 95.22%
##[warning]Free memory is lower than 5%; Currently used: 95.22%
##[warning]Free memory is lower than 5%; Currently used: 95.22%
##[warning]Free memory is lower than 5%; Currently used: 95.22%
##[warning]Free memory is lower than 5%; Currently used: 95.22%
  System.Runtime.Tests -> /__w/1/s/artifacts/bin/System.Runtime.Tests/Debug/net9.0-browser/browser-wasm/publish/
  export XUNIT_HIDE_PASSING_OUTPUT_DIAGNOSTICS=1

```
Not a huge issue, but is likely slowing the build down, and looks like something has changed.

**Comment by SingleAccretion** [comment]
Observations from looking at the recent runs:
1) This looks to be `browser-wasm linux debug`-specific.
2) Happens during the libraries tests compilation.
3) Happens _after_ ILC, so most likely the memory hog here is clang (more or less expected).

Currently, ILC produces 8 bitcode files for each compilation, which are then processed in parallel. Peak memory consumption is therefore a function of `min(NumberOfCores, 8) * (size / 8)`, for each project in isolation.

Further, libraries test projects are built in parallel themselves, so if our machine has 16 cores, peak memory consumption can be as much as double that of a single project.

Possible mitigations:
1) Increase the number of bitcode files, so that we saturate cores with smaller pieces of work.
2) Disable building the libraries tests projects in parallel, so that our peak memory consumption is always proportional to the largest project's size.

`1` should have a neutral effect on the build in terms of speed, while `2` will slow it down, so it seems like the better option (assuming it works, of course).

The one problem with all this is that from the logs, it looks like the OOM condition happens during the compilation of `S.R.Tests` (expected, this is the largest test) _in isolation_, with all other tests already compiled.

**Comment by yowl** [comment]
1 seems like it would work, and should be easy to try.  Shall I do that?

**Comment by SingleAccretion** [comment]
> 1 seems like it would work, and should be easy to try. Shall I do that?

Sure.
