### ISSUE TITLE
[NativeAOT-LLVM] Compile minimum wasm file size

### ISSUE THREAD

**Issue by vlmoon99** [dotnet/runtimelab#2789]
Hi there,

I'm very inspired by what you are doing with WASM and the feature/NativeAOT-LLVM. I'm trying to build a minimal WASM file size. Currently, I'm stuck at 4.3 MB in total. I tried to exclude some DLLs, but it didn’t work. 

I have a small example in Zig:

**env.zig**:
```zig
pub extern "env" fn storage_read(u64, u64, u64) u64;
pub extern "env" fn storage_write(u64, u64, u64, u64, u64) u64;
pub extern "env" fn storage_has_key(u64, u64) u64;

pub extern "env" fn read_register(u64, u64) void;

pub extern "env" fn value_return(u64, u64) void;
pub extern "env" fn log_utf8(u64, u64) void;

pub fn log(str: []const u8) void {
  const ptr = @as(u64, @ptrToInt(str.ptr));
  log_utf8(str.len, ptr);
}
```

**main.zig**:
```zig
const env = @import("env.zig");

export fn hello_world() void {
    env.log("hello world");
}
```

I want to reproduce this in C# with a minimal runtime environment and be able to include only the .NET DLLs I need. I tried to do it manually in my `csproj` file, but it didn’t work with the HelloWorld example—I still see the same .NET DLLs I tried to exclude. 

Please help me compile a file smaller than 1 MB. How can I achieve this?

**Comment by SingleAccretion** [comment]
What are your compilation settings?

As we note in [documentation](https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/docs/using-nativeaot/compiling.md#webassembly-application-configuration), the two largest size contributors are ICU and debug info.

It is expected that NAOT-LLVM HelloWorld is around ~1MB with these omitted. For example, compiling our [HelloWorld sample](https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/samples/HelloWorld/HelloWorld.csproj) with:
```
dotnet publish -r browser-wasm /p:DebugType=none /p:InvariantGlobalization=true
```
I get a ~900KB file. Further optimization is possible with [documented upstream switches](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/optimizing). For example, with:
```
dotnet publish -r browser-wasm /p:DebugType=none /p:InvariantGlobalization=true /p:OptimizationPreference=Size /p:StackTraceSupport=false
```
HelloWorld becomes ~770 KB in size (note I am counting only the `.wasm` size here).

The numbers for `-r wasi-wasm` are similar but a bit larger because WASI runtimes don't implement the exception handling proposal yet.

**Comment by vlmoon99** [comment]
@SingleAccretion Thanks for your support, I forgot to remove the Debug option from the compilation.
