### ISSUE TITLE
Malformed function table in unwind from HijackCallback

### ISSUE THREAD

**Issue by emily33901** [dotnet/runtimelab#343]
Hi,
Recently I have been attempting to upgrade my setup from corert -> NativeAOT and have encountered a few problems. The main blocking point right now is 
```
Exception thrown at 0x00007FFD823D1ED6 (ntdll.dll) in <process>.exe: 0xC00000FF: A malformed function table was encountered during an unwind operation.
```

Which occurs after a GC call tries to hijack threads - so far I have seen it across a number of different threads that run (originally I thought that it might just be limited to the native thread that I was hijacking from the process im in but it turns out that it also happens on nativeAOT made threads).

The top of the callstack is always the following:
![](https://i.f1ssi0n.com/ContortedSicklyAnhinga.png)
For some further insight here is the bottom of the stack
![](https://i.f1ssi0n.com/UngreenedHerbyKookaburra.png)
And further insight here is where it fails: Blurred name for the exe is the process which my dll is sitting in.
![](https://i.f1ssi0n.com/PseudopropheticCadetblueLion.png)

Im not entirely sure why this is happening, but it could be because of being in another process which has its own threads and seh handling for those... This crash also destroys the process and leaves it in an undefined state with no modules, no memory, and no threads.

Any help would be highly appreciated.

Thanks,
Em

**Comment by jkotas** [comment]
Thank you for reporting this crash.

Could you please find value of `pRegisterSet->IP` that is passed as an argument into `RtlVirtualUnwind`, and then find the method that is at this address? It is the method that has the problem.

The bug is most likely caused by the compiler producing bad code/unwind info for some method. We need to find the name of the method and go from there.

I understand that it may not be an option for you, but I will mention it anyway: If you would be willing to share the crash dump and symbols privately, I would be happy to take a look. My email address is in my github profile.

**Comment by emily33901** [comment]
Yeah will get that to you asap - putting tracepoints on rtlvirtualuinwind is quite slow however. Do you have any better recommendations instead of putting a tracepoint on that without straight up trying to self compile the native runtime? Maybe its worth it in the end however.

**Comment by jkotas** [comment]
You should be able to find the value once the program crashed.

**Comment by emily33901** [comment]
Dont think I can because i dont have the source code for it so it will only keep track of the registers... I dont remember them changing when i changed through from the ntdll call to the rtlvirtualunwind call

**Comment by jkotas** [comment]
Closing inactive issues.
