### ISSUE TITLE
Make compilation errors during source generation more verbose to the user

### ISSUE THREAD

**Issue by kevinwkt** [dotnet/runtimelab#44]
Currently within the feature, if the compilation fails in the generation phase, only a generic message is given to the user.

Let's investigate a way to inject messages to roslyn's output compilation warnings during source generations and standarize output messages to the user.

**Comment by am11** [comment]
Here is the related section from the cookbook: https://github.com/dotnet/roslyn/blob/1309e6b088a884104057b7614389493d436b3aee/docs/features/source-generators.cookbook.md#issue-diagnostics.

ps: this issue is appearing under [`Done` column](https://github.com/dotnet/runtimelab/projects/1#card-43064840), is that correct?

**Comment by kevinwkt** [comment]
Yes, currently descriptors are defined [here](https://github.com/dotnet/runtimelab/blob/JsonCodeGen/src/libraries/System.Text.Json/System.Text.Json.SourceGeneration/JsonSourceGeneratorDiagnostics.cs#L9) and we are currently using ```context.ReportDiagnostic``` as instructed [here](https://github.com/dotnet/runtimelab/blob/JsonCodeGen/src/libraries/System.Text.Json/System.Text.Json.SourceGeneration/JsonSourceGenerator.cs#L92).

Thanks, will move this issue to done.
