### ISSUE TITLE
[ NativeAOT ] error MSB4057: The target "PrepareForILLink" does not exist in the project

### ISSUE THREAD

**Issue by FoggyFinder** [dotnet/runtimelab#590]
Unable to build a solution anymore.

I've found PR #547 where in one comment was mentioned that "_I assume it will no longer work withe .NET Core 3.1 SDK._"

So there is no way to use CoreRt/NativeAOT with .Net Core 3.1, right? If so 

* shouldn't be the error message more clear ?
* shouldn't be the section [Know issues](https://github.com/dotnet/runtimelab/tree/feature/NativeAOT/samples/HelloWorld#know-issues) (I suppose there is a typo `Know**n**`) updated / removed in such case ?

Otherwise the Q is how to fix it ?

**Comment by MichalStrehovsky** [comment]
Yes, I wanted to add a more clear error message but got stuck figuring out the MSBuild goo to say ".NET 5 or later". I updated [prerequisites](https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/samples/prerequisites.md) to say .NET 5 is needed but nobody reads all documentation. We should definitely delete the "how to use with .NET Core 2.1" since nobody tests that.

**Comment by MichalStrehovsky** [comment]
We might also be able to say in the ILCompiler NuGet package that .NET 5 is required so that this fails during restore.

This also has the problem that I don't know off the top of my head where to do that. The NuGet building infrastructure the ILCompiler package hooks into is... complex.

**Comment by jkotas** [comment]
We should really only need .NET 5 SDK. I do not think there is a problem with targeting older `TargetFramework` that the nuget restore is based on.

**Comment by jkotas** [comment]
The error message has been improved.
