### ISSUE TITLE
NETSDK1148 when using NativeAOT

### ISSUE THREAD

**Issue by wjk** [dotnet/runtimelab#771]
Please see the attached zipped binlog. It complains that I have two files named `apphost.exe` when, in fact, I have one copy of `apphost.exe`; the other is named `x2copy.exe`, and is my all-native executable product as output by NativeAOT. This did not happen before, but I cannot say when it started, as I only run NativeAOT when cutting a release, which is not very often. I am using NativeAOT version 6.0.0-preview.3.21153.3, as downloaded automatically by NuGet when running the Restore task. Any pointers would be appreciated. Thanks!

[Here is the zipped binlog](https://github.com/dotnet/runtimelab/files/6087806/msbuild.binlog.zip).

**Comment by jkotas** [comment]
Thank you for the report. This caused by a new check added to SDK in https://github.com/dotnet/sdk/pull/14020 that is not compatible with how NativeAOT plugs into the publish pipeline.

You can workaround this by adding `/p:ErrorOnDuplicatePublishOutputFiles=false` to your publish command line for now. A package with the workaround integrated should be available in a day or so.

**Comment by jkotas** [comment]
The package with the fix is published now.
