### ISSUE TITLE
Question about typeof().Guid

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtimelab#802]
When implementing tests I have approximate code
```
[ComImport]
[ComVisible(true)]
[Guid("D6DD68D1-86FD-4332-8666-9ABEDEA2D24C")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public interface IComInterface
{
    void DoWork();
}

////

internal static Guid IComInterface_GUID = typeof(IComInterface).GUID;
```

This throws 
```
Unhandled Exception: System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
 ---> System.Reflection.MissingMetadataException: 'PInvokeTests.IComInterface' is missing metadata. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=392859
   at System.Reflection.Runtime.TypeInfos.RuntimeBlockedTypeInfo.get_GUID() + 0x42
```

I was not expecting that this cause any issues. Especially that I have that pattern in other project. Do tests have more aggressive NativeAOT settings then defaults?

**Comment by jkotas** [comment]
Yes, the tests have more restrictive reflection settings than the default.

**Comment by kant2002** [comment]
I understand that in general sense it is not possible to have `typeof(XXX).GUID` properly working, but can compiler ensure that if typeof operates on the well-known type which explicitly has `GuidAttribute` set, then this expression would be precomputed?

**Comment by jkotas** [comment]
@MichalStrehovsky ?

**Comment by MichalStrehovsky** [comment]
> at System.Reflection.Runtime.TypeInfos.RuntimeBlockedTypeInfo.get_GUID()

`RuntimeBlockedTypeInfo` means that reflection blocking is active. The pinvoke test opts into that for its main assembly:

https://github.com/dotnet/runtimelab/blob/b1b2410a7e8dccba5f643ab43c8e7a4f5da3ad0a/src/tests/nativeaot/SmokeTests/PInvoke/PInvoke.cs#L15-L20

If you need to do reflection-y things, you either need to add another assembly to the pinvoke test (the attribute is applicable per assembly), or just add a new test.

> I understand that in general sense it is not possible to have typeof(XXX).GUID properly working

I think in the general sense this should just work. The problem is opting into reflection blocking. We do that as a size optimization for some of the System.Private assemblies only. ...and in this test.

**Comment by jkotas** [comment]
I think it would be nice to just avoid reflection-y things for the ComWrappers test.
