### ISSUE TITLE
Interned strings don't have same identity as string literals

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtimelab#823]
Failing the System.Tests.StringTests.InternTest System.Runtime test.

We could probably fix this by walking the frozen objects region, looking for all strings in it and adding them to the intern table on first `String.Intern` call.

**Comment by jkotas** [comment]
NGen in .NET Framework did not guarantee this either and it have not ever showed up as a problem (except for empty string). 

For example:
```
using System;

Console.WriteLine(object.ReferenceEquals(string.Intern(new string('a', 3)), "aaa"));
```
Prints `true` with JIT, but prints 'false' when ngened in .NET Framework. 

I think we should make sure that this works for empty string, but otherwise move it into dotnet/runtime#69919

**Comment by MichalStrehovsky** [comment]
Should we fix the test so that it only checks for string.Empty and nothing else?

I just realized that this is probably `CompilationRelaxations.NoStringInterning` - the C# compiler puts that attribute by default so this is a legal optimization for any runtime to do.

**Comment by jkotas** [comment]
> Should we fix the test so that it only checks for string.Empty and nothing else?

`InternalTestAotSubset` (that should be `InternTestAotSubset`) does that. I guess disable the test for native AOT?
