### ISSUE TITLE
NativeAOT-LLVM: IR: CALL help byref  HELPER.CORINFO_HELP_READYTORUN_STATIC_BASE

### ISSUE THREAD

**Issue by yowl** [dotnet/runtimelab#839]
I'm looking to extend the IR support to cover 
https://github.com/dotnet/runtimelab/blob/0821949839aefc3cb69752d2cbbdaf64d33c3863/src/tests/nativeaot/SmokeTests/HelloWasm/HelloWasm.cs#L646-L649
This is pretty trivial IL, although expands to cover a few hidden extras as can be seen from the current LLVM:
```
define void @HelloWasm_Program__KillParent(i8* %0) !dbg !483989 {
Prolog:
  br label %Block0

Block0:                                           ; preds = %Prolog
  call void @llvm.donothing(), !dbg !483990
  %LoadAddressOfSymbolNode = load i32*, i32** @__GCStaticBase_HelloWasm_Program___SYMBOL, align 4, !dbg !483991
  %castBasePtrPtr = bitcast i32* %LoadAddressOfSymbolNode to i8***, !dbg !483991
  %basePtr = load i8**, i8*** %castBasePtrPtr, align 4, !dbg !483991
  %base = load i8*, i8** %basePtr, align 4, !dbg !483991
  %LoadAddressOfSymbolNode1 = load i32*, i32** @__NonGCStaticBase_HelloWasm_Program___SYMBOL, align 4, !dbg !483991
  %classConstructionContext = getelementptr i32, i32* %LoadAddressOfSymbolNode1, i32 -2, !dbg !483991
  %1 = getelementptr i8, i8* %0, i32 0, !dbg !483991
  %CastPtrclassConstructionContext = bitcast i32* %classConstructionContext to %"[S.P.CoreLib]System.Runtime.CompilerServices.StaticClassConstructionContext"*, !dbg !483991
  call void @S_P_CoreLib_System_Runtime_CompilerServices_ClassConstructorRunner__EnsureClassConstructorRun(i8* %1, %"[S.P.CoreLib]System.Runtime.CompilerServices.StaticClassConstructionContext"* %CastPtrclassConstructionContext), !dbg !483991
  %aParent_addr = getelementptr i8, i8* %base, i32 4, !dbg !483991
  %shadowStackTop = getelementptr i8, i8* %0, i32 0, !dbg !483991
  store i8* %shadowStackTop, i8** @t_pShadowStackTop, align 4, !dbg !483991
  call void @RhpAssignRef(i8* %aParent_addr, i8* null), !dbg !483991
  ret void, !dbg !483991
}
```
The LIR for this is
```
------------ BB01 [000..008) (return), preds={} succs={}
               [000008] ------------                 IL_OFFSET void   IL offset: 0x0
N001 (  1,  1) [000000] ------------                 NO_OP     void
N001 ( 14,  2) [000002] H-CXG-------         t2 =    CALL help byref  HELPER.CORINFO_HELP_READYTORUN_STATIC_BASE
N002 (  1,  1) [000003] ------------         t3 =    CNS_INT   int    8 Fseq[aParentOfStructWithObjRefs]
                                                  /--*  t2     byref
                                                  +--*  t3     int
N003 ( 15,  3) [000004] ---XG--N----         t4 = *  ADD       byref
N005 (  1,  1) [000001] ------------         t1 =    CNS_INT   ref    null
                                                  /--*  t4     byref
                                                  +--*  t1     ref
               [000009] -ACXG-------              *  STOREIND  ref
N001 (  0,  0) [000007] ------------                 RETURN    void
```
The `CALL help byref  HELPER.CORINFO_HELP_READYTORUN_STATIC_BASE` is the `@__GCStaticBase_HelloWasm_Program___SYMBOL` in the LLVM but in the LIR the call doesn't seem to have the type parameter, is it implicit?

**Comment by jkotas** [comment]
Yes, it is implicit. There are variants with explicit type parameters used for the JIT path. It may be ok to use those for wasm/llvm instead.

**Comment by MichalStrehovsky** [comment]
We don't have a good/fast way to get the the static bases from a the type handle in NativeAOT - this info doesn't hang off the EEType structure - but it can be done if really needed. The CoreCLR helper structure (the helper is used in CoreCLR jitted code) is not ideal.

We previously attempted the make RyuJIT not require these helpers on NativeAOT and inline what the helper is doing ([previously](https://github.com/dotnet/corert/pull/3962) ([RyuJIT change](https://github.com/dotnet/coreclr/pull/12420)), [previously](https://github.com/dotnet/corert/pull/5131)) but neither attempt panned out because of lack of focus. But this is an alternative approach - fix JitInterface/RyuJIT to inline what the helper is doing and then we don't need a helper.

There are a couple more "handwritten" helpers like this, but those can be avoided by passing `--scan` to the compiler - the compiler will run a scanning phase before starting compilation and collect knowledge necessary for those helpers to get inlined. (They're helpers like "vtcall to `Object.ToString`" - we don't know the slots of virtual methods until we either finish compiling, or let the scanner run.)

**Comment by yowl** [comment]
@MichalStrehovsky in https://github.com/dotnet/corert/pull/5131#issuecomment-352587882 it talks about hitting an assert.  I've merged the changes from that PR into the current codebase (or nearly current) and it passes the tests.  Was the assert happening elsewhere do you remember?

**Comment by MichalStrehovsky** [comment]
I wouldn't be surprised if the underlying issue got fixed - this was a RVA statics codepath and those are pretty rare; but the C# compiler recently stared to generate more of these as an optimization for `static ReadOnlySpan<byte> myField = new byte[] { 1, 2, 3, 4, 5 }` so it gets exercised more regularly on CoreCLR too.

**Comment by yowl** [comment]
Thanks.  Leaves the comment https://github.com/dotnet/corert/pull/5131#issuecomment-352765429 about "it would be better to keep providing baseAddress + offset".  Clearly just providing the `Offset` property is not enough.  Is this a big change to the PR that maybe I could do?  I'm thinking that starting with nonGC statics for LLVM would be easier.  

Alternatively, if this is just going to be me, asking you a lot of questions, then maybe I should go with the other option of using the other variants for now, which looks like it might be switching the flow around here, and maybe other places.

https://github.com/dotnet/runtimelab/blob/bd215e1ff87ed33bc5645d2d572088e2a16c3965/src/coreclr/jit/importer.cpp#L7526-L7545

**Comment by MichalStrehovsky** [comment]
Well the thing is that if you want to get the helper that gets a static base out of an EEType implemented, you'll either need to change the EEType structure to have that information, or call into the runtime type loader to get it out of the hash tables. The runtime type loader is written in C# and it does use statics as well, so it requires some refactoring to avoid recursions.

> "it would be better to keep providing baseAddress + offset". Clearly just providing the Offset property is not enough.

Yeah, so this would be a JitInterface change and I'm not 100% clear on how the API shape would look like. We can try this one if you're okay with me potentially sending you to a (couple?) dead end(s) before we find what really works. I think this option is best for the product because it improves things across all existing NativeAOT RyuJIT targets. But it might be more work.

I'm also wondering - how are you representing situations when RyuJIT-produced LLVM bitcode needs to reference compiler generated LLVM bitcode (e.g. when RyuJIT needs to get the address of an EEType)? Would that scheme also work for code? If so, maybe we could keep doing what we're doing - have ILCompiler.LLVM call into the LLVM C API to create the helpers with the expected shape and RyuJIT would just refer to them through symbols.

**Comment by yowl** [comment]
Maybe I've over complicated things.  I'm going to end up with something like this in RyuJit
```
    GenTreeCall* gtCall = node->AsCall();
    if (gtCall->gtCallType == CT_HELPER)
    {
        if (gtCall->gtCallMethHnd == _compiler->eeFindHelper(CORINFO_HELP_READYTORUN_STATIC_BASE))
        {
            const char* symbolName = (*_getMangledSymbolName)(_thisPtr, _info.compMethodHnd);
            llvm::GlobalValue* symbol = _module->getNamedValue(symbolName);
            if (symbol == nullptr)
            {
                symbol = new llvm::GlobalVariable(*_module,
                    llvm::Type::getInt32PtrTy(_llvmContext),
                    /*isConstant=*/true,
                    llvm::GlobalValue::ExternalLinkage,
                    /*Initializer=*/0, 
                    symbolName);
            }
            return symbol;
        }
        else fatal(CORJIT_SKIPPED);
    }
    else fatal(CORJIT_SKIPPED);
```
So it will just be an external symbol that I am trying to get by calling back into the ILCompiler and all I need returned is the name (and type but that is always i32*).  The problem with this logic is that there is a lot more in the ILCompiler, checks for RVA/ThreadStatic/GC/NonGC using the `FieldDesc`.  If I could determine these conditions from the LIR, then I think I'd be ok, and I don't mind not supporting most of them for now, but I'd need to still detect them so I can fail.

**Comment by MichalStrehovsky** [comment]
The `gtEntryPoint.addr` field on the call is going to point to the specific helper that you could use to disambiguate between the various bases.

But couldn't you just add a:

```
        [UnmanagedCallersOnly]
        public static byte* getSymbolMangledName(IntPtr thisHandle, void* handle)
        {
            var _this = GetThis(thisHandle);

            var node = (ISymbolNode)_this.HandleToObject(handle);
            Utf8StringBuilder sb = new Utf8StringBuilder();
            node.AppendMangledName(_this._compilation.NameMangler, sb);
            return (byte*)_this.GetPin(sb.UnderlyingArray);
        }
```

That you would call that on the `gtCall->gtEntryPoint.addr` that you have for the helper? This would give you a name of the symbol. You just generate a call to this extern symbol.

Now we only have a problem with who should define the symbol.

We could just do what `GetCodeForReadyToRunGenericHelper` in WASM is already doing - just define the helper from the compiler, using the C API, mirroring what we do with the helper in "handwritten" assembly.

**Comment by yowl** [comment]
@MichalStrehovsky Super, thanks!

So I'll be replacing the inlined LLVM code that I have above, with a call.  I just leave whether that would be better inlined to the emscripten/llvm optimisers?

**Comment by MichalStrehovsky** [comment]
Yes - these are all helper calls in the other NativeAOT RyuJIT targets. It ends up being a bit slower than CoreCLR jitted code but in the end it doesn't matter that much. Hopefully we'll get to the RyuJIT mini feature to inline them in the future.

**Comment by yowl** [comment]
One last thing, how or where does `ReadyToRunHelperNode` get added as a dependency?
