### ISSUE TITLE
Infinite recursion in SR.GetResourceString when using debug ILCompiler build

### ISSUE THREAD

**Issue by AntonLapounov** [dotnet/runtimelab#987]
Create a console app containing just this line:
```C#
new System.SystemException();
```
and compile it in release mode with a **debug** build of the ILCompiler package:
```cmd
dotnet publish -r win-x64 -c Release
```
If you run it, the app goes into infinite recursion in the `SR.GetResourceString` method, eventually failing due to stack overflow (that takes a long time though):
```
...
Repro!S_P_CoreLib_System_Diagnostics_Debug__Fail_0
Repro!S_P_CoreLib_System_Diagnostics_Debug__Assert_1
Repro!S_P_CoreLib_System_Diagnostics_Debug__Assert
Repro!S_P_TypeLoader_Internal_Runtime_TypeLoader_TypeLoaderEnvironment__TryGetStaticClassConstructionContext
Repro!S_P_Reflection_Execution_Internal_Reflection_Execution_ReflectionExecutionDomainCallbacksImplementation__TryGetStaticClassConstructionContext
Repro!S_P_CoreLib_System_Runtime_CompilerServices_RuntimeHelpers__RunClassConstructor
Repro!S_P_CoreLib_System_SR__InternalGetResourceString
𝗥𝗲𝗽𝗿𝗼!𝗦_𝗣_𝗖𝗼𝗿𝗲𝗟𝗶𝗯_𝗦𝘆𝘀𝘁𝗲𝗺_𝗦𝗥__𝗚𝗲𝘁𝗥𝗲𝘀𝗼𝘂𝗿𝗰𝗲𝗦𝘁𝗿𝗶𝗻𝗴_𝟬
Repro!S_P_CoreLib_System_Diagnostics_StackFrame__AppendToStackTrace
Repro!S_P_CoreLib_System_Diagnostics_StackTrace__ToString
Repro!S_P_CoreLib_System_Diagnostics_StackTrace__ToString_1
Repro!S_P_CoreLib_System_Diagnostics_DebugProvider__Fail
Repro!S_P_CoreLib_System_Diagnostics_Debug__Fail_0
Repro!S_P_CoreLib_System_Diagnostics_Debug__Assert_1
Repro!S_P_CoreLib_System_Diagnostics_Debug__Assert
Repro!S_P_TypeLoader_Internal_Runtime_TypeLoader_TypeLoaderEnvironment__TryGetStaticClassConstructionContext
Repro!S_P_Reflection_Execution_Internal_Reflection_Execution_ReflectionExecutionDomainCallbacksImplementation__TryGetStaticClassConstructionContext
Repro!S_P_CoreLib_System_Runtime_CompilerServices_RuntimeHelpers__RunClassConstructor
Repro!S_P_CoreLib_System_SR__InternalGetResourceString
𝗥𝗲𝗽𝗿𝗼!𝗦_𝗣_𝗖𝗼𝗿𝗲𝗟𝗶𝗯_𝗦𝘆𝘀𝘁𝗲𝗺_𝗦𝗥__𝗚𝗲𝘁𝗥𝗲𝘀𝗼𝘂𝗿𝗰𝗲𝗦𝘁𝗿𝗶𝗻𝗴_𝟬
Repro!S_P_CoreLib_System_SystemException___ctor
Repro!Repro__Module___StartupCodeMain
Repro!wmain
Repro!invoke_main
Repro!__scrt_common_main_seh
Repro!__scrt_common_main
Repro!wmainCRTStartup
KERNEL32!BaseThreadInitThunk
ntdll!RtlUserThreadStart
```
That is caused by the failed assertion in `TypeLoaderEnvironment.TryGetStaticClassConstructionContext` for the `System.Resources.ResourceReader` type: https://github.com/dotnet/runtimelab/blob/4ab2b2bad7f3d1befab60448ed0b4d0a1b3e5c29/src/coreclr/nativeaot/System.Private.TypeLoader/src/Internal/Runtime/TypeLoader/TypeLoaderEnvironment.Metadata.cs#L458-L460
To create a debug ILCompiler package, I used the following commands:
```cmd
build -arch x64 -c Release -s nativeaot
build -arch x64 -lc Release -s nativeaot+libs+nativeaot.packages
```
The first command was needed to avoid the following error (which is probably a separate issue):
```
CSC : error CS2001: Source file 'artifacts\obj\coreclr\nativeaot\System.Private.CoreLib\..\..\windows.x64.Release\nativeaot\Runtime\Full\AsmOffsets.cs' could not be found. [src\coreclr\nativeaot\System.Private.CoreLib\src\System.Private.CoreLib.csproj]
```

**Comment by MichalStrehovsky** [comment]
https://github.com/dotnet/runtimelab/blob/4ab2b2bad7f3d1befab60448ed0b4d0a1b3e5c29/src/coreclr/nativeaot/System.Private.TypeLoader/src/Internal/Runtime/TypeLoader/TypeLoaderEnvironment.Metadata.cs#L458-L460

We can now reach the assertion whenever IL Linker would have not considered the cctor to be visible from reflection.

That said, there's a bug in the dataflow analysis in this case: some places under ILCompiler.Compiler\Compiler\Dataflow that check for `.IsConstructor` should be also checking for `.IsStaticConstructor` to keep the constructor visible (dataflow models the reflection behavior and under reflection, static constructors are also constructors).

**Comment by MichalStrehovsky** [comment]
My quick analysis was wrong - RunClassConstructor is not annotated to keep private constructors because it takes RuntimeTypeHandle as input and we can't annotate RuntimeTypeHandle. This is just an intrinsic.

The problem happens because we don't propagate the fact that a cctor is needed from the scanning phase (where dataflow analysis happens) to the compilation phase. The type has no reflectable static fields that would root it.

In the below program we don't generate a non-GC static base for TypeWithCctor because it wasn't needed anywhere. But RunClassConstructor needs it.

We probably need a new node type to pipe that information through.

Alternatively we can just revert #541 because this is exactly one of the useless cctors that the optimization removed.

```csharp
    class TestRunClassConstructor
    {
        sealed class TypeWithCctor
        {
            static TypeWithCctor()
            {
                CctorRan = true;
            }

            public TypeWithCctor(int preventDefaultConstructor) { }
        }

        private static bool CctorRan;

        public static void Run()
        {
            System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(typeof(TypeWithCctor).TypeHandle);
            if (!CctorRan)
                throw new Exception();
        }
    }
```

**Comment by jkotas** [comment]
Is it also a problem for IL linker? Can the IL linker drop the static constructor when there is nothing else rooting it? If it is the case, we should mark this API as RequiresUnreferencedCode and move on with life.

I think it should be ok to delete the `RunClassConstructor` calls from CoreLib's SR.cs. They are a left-over from hardening for SQL server and it is unlikely they are still effective.

**Comment by MichalStrehovsky** [comment]
IL Linker would strip it if it's not necessary for anything else statically. It detects RunClassConstructor as an intrinsic, same as NativeAOT:

https://github.com/mono/linker/blob/1dfcf3077aca1ea77850f409d95c3192f03507b3/src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs#L1630-L1648

If the type cannot be determined statically, it just warns when RunClassConstructor was called.

In this case we can detect it and we do. The problem is that in optimized builds we run the dataflow scanner as part of the scanning phase and we don't have a way to communicate to the compilation phase that the cctor is needed (or more precisely, the non-GC static base is needed because we need the cctor context data structure). We currently only communicate back the reflected on types, methods, and fields.
